// BlueprintGeneratedClass BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C
// Size: 0x47c (Inherited: 0x46a)
struct ABP_AreaLoadEventFunction_C : ABP_MakeEventActorBase_C {
	char pad_46A[0x2]; // 0x46a(0x02)
	int32_t Location; // 0x46c(0x04)
	int32_t Area; // 0x470(0x04)
	int32_t NewVar_1; // 0x474(0x04)
	int32_t NewVar_2; // 0x478(0x04)

	void PostLoad_L22A11(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A11 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A09(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A09 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A08(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A08 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A07(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A07 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A04(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A04 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L21A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L21A03 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L21A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L21A02 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A05(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A05 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RegisterRetryTips(bool isRegisted); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.RegisterRetryTips // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L30A01(bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L30A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L07A03(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L07A03 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L15A01(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L15A01 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L60A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L60A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L07A52(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L07A52 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L14A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L14A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L22A02(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L22A02 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L22A01(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L22A01 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A10(int32_t Variation, bool Is First Try, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A10 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A06(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A06 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A02(int32_t Variation, bool Is First Try, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L22A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L22A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L15A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L15A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L10A03(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L10A03 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L10A02(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L10A02 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L10A01(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L10A01 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L31A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L31A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L10A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L10A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L10A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L10A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L10A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L10A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L23A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L23A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L17A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L17A03 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L17A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L17A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L21A04(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L21A04 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L21A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L21A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L20A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L20A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CheckPortal(struct FName PortalName, bool Equal); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.CheckPortal // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L19A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L19A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L18A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L18A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L29A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L29A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L12A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L12A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L12A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L12A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L12A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L12A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L56A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L56A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L13A04(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L13A04 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L13A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L13A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L13A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L13A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L08A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L08A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L08A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L08A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L08A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L08A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L09A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L09A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L09A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L09A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L01A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L01A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L01A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L01A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L07A03(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L07A03 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L07A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L07A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_Common(int32_t Location, int32_t Area, int32_t PortalID, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_Common // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreLoad_L07A01(int32_t Location, int32_t Area, int32_t OutLocation, int32_t OutArea, int32_t OutVariation); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PreLoad_L07A01 // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L07A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L07A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L06A02(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L06A02 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PostLoad_L06A01(int32_t Variation, bool IsFirstTry, bool Initialized); // Function BP_AreaLoadEventFunction.BP_AreaLoadEventFunction_C.PostLoad_L06A01 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

