// BlueprintGeneratedClass BPFL_CharacterUtility.BPFL_CharacterUtility_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_CharacterUtility_C : UBlueprintFunctionLibrary {

	void IsAttackedByMainPlayer(struct FHCHitResult HitResult, struct UObject* __WorldContext, bool bMainPlayer); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.IsAttackedByMainPlayer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|Const) // @ game+0x1685580
	void SetRestrictDriveBegin(bool bRestrict, struct UObject* __WorldContext, bool bDummy); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.SetRestrictDriveBegin // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CameraAttentionEndForActor(struct UCurveFloat* ActorCurveOut, struct UCurveFloat* FovCurveOut, struct UObject* __WorldContext, bool bDummy); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.CameraAttentionEndForActor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CameraAttentionStartForActor(struct AActor* TargetActor, struct UCurveFloat* ActorCurveIn, bool ChangeFov, float TargetFov, struct UCurveFloat* FovCurveIn, bool bEnableOffsetAngleVt, float OffsetAngleVtIn, bool bEnableOffsetDist, float OffsetDistIn, struct UObject* __WorldContext, bool bDummy); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.CameraAttentionStartForActor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangePlayerLockTarget(struct ARSBattleCharacter_C* Src, struct ARSBattleCharacter_C* dst, struct UObject* __WorldContext, bool bChange); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.ChangePlayerLockTarget // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetGenderTypeForCharaID(struct FString CharaID, struct UObject* __WorldContext, enum class ETextGender TextGenderType); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.GetGenderTypeForCharaID // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RestoreCharacterParameter(struct FCopyCharacterParameterStruct BackupData, struct ARSBattleCharacter_C* Character, bool bRestoreTable, bool bRestoreBasic, bool bResetCrash, struct UObject* __WorldContext, bool bDummy); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.RestoreCharacterParameter // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void BackupCharacterParameter(struct ARSBattleCharacter_C* BaseCharacter, bool bBackupTable, bool bBackupBasic, struct UObject* __WorldContext, struct FCopyCharacterParameterStruct BackupData); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.BackupCharacterParameter // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetTarget2CamaraOffsetLocation(struct FVector TargetLocation, float Offset, struct UObject* __WorldContext, struct FVector Location); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.GetTarget2CamaraOffsetLocation // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|Const) // @ game+0x1685580
	void GetGroundLocation(struct FVector baseLocation, struct UObject* __WorldContext, bool bFind, struct FVector Location); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.GetGroundLocation // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|Const) // @ game+0x1685580
	void GetCamaraEyeOffsetLocation(float Offset, struct UObject* __WorldContext, struct FVector Location); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.GetCamaraEyeOffsetLocation // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|Const) // @ game+0x1685580
	void GetNearestPlayerSideCharacter(struct ARSBattleCharacter_C* BaseChara, float limitDistance, struct UObject* __WorldContext, struct ARSBattleCharacter_C* findChara, float Distance); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.GetNearestPlayerSideCharacter // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|Const) // @ game+0x1685580
	void CanTelepoPlayer(struct AActor* Character, struct UObject* __WorldContext, bool CanDo); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.CanTelepoPlayer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x1685580
	void GetAttackOwner(struct FHCHitResult HitResult, struct UObject* __WorldContext, struct AActor* Owner); // Function BPFL_CharacterUtility.BPFL_CharacterUtility_C.GetAttackOwner // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|Const) // @ game+0x1685580
};

