// BlueprintGeneratedClass BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_GameInstanceFunctionLibrary_C : UBlueprintFunctionLibrary {

	struct ARSParticleSystemManager* GetParticleSystemManager(struct UObject* __WorldContext); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetParticleSystemManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	struct ASASManager* GetSASManager(struct UObject* __WorldContext); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetSASManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	struct AIntroTutorialManager* GetIntroTutorialManager(struct UObject* __WorldContext); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetIntroTutorialManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	struct AActor* GetLevelManager(struct UObject* __WorldContext); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetLevelManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	struct AActor* GetEventManager(struct UObject* __WorldContext); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetEventManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetBrainTalkManager(struct UObject* __WorldContext, struct ABrainTalkManager* BrainTalkManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetBrainTalkManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetLC21MapGimmickManager(struct UObject* __WorldContext, struct ALC21MapGimmickManager* MapGimmickManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetLC21MapGimmickManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMapGimmickManager(struct UObject* __WorldContext, struct AMapGimmickManager* MapGimmickManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetMapGimmickManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetFinishMoveManager(struct UObject* __WorldContext, struct AActor* FinishMove Manager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetFinishMoveManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetSaveLoadParamClassManager(struct UObject* __WorldContext, struct USaveLoadParamClassManager* SaveLoadParamClassManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetSaveLoadParamClassManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMessageHudManager(struct UObject* __WorldContext, struct AMessageHudManager* MessageHudManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetMessageHudManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetArrangeItemManager(struct UObject* __WorldContext, struct AArrangeItemManager* ArrangeItemManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetArrangeItemManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetDropItemManager(struct UObject* __WorldContext, struct ADropItemManager* Drop Item Manager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetDropItemManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetDatabaseManager(struct UObject* __WorldContext, struct UDatabaseManager* Manager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetDatabaseManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetDebuggingManager(struct UObject* __WorldContext, struct AActor* DebuggingManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetDebuggingManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetUserParamManager(struct UObject* __WorldContext, struct UUserParamManager* UserParamManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetUserParamManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetSceneManager(struct UObject* __WorldContext, struct AActor* SceneManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetSceneManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetBSPManager(struct UObject* __WorldContext, struct AActor* BSPManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetBSPManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetBattlefieldManager(struct UObject* __WorldContext, struct ABattlefieldManager* BattlefieldManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetBattlefieldManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetEnemyManager(struct UObject* __WorldContext, struct AEnemyManager* EnemyManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetEnemyManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetPlayerManager(struct UObject* __WorldContext, struct APlayerManager* PlayerManager); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetPlayerManager // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetRSGameInstance(struct UObject* __WorldContext, struct URSGameInstance* RSGameInstance); // Function BPFL_GameInstanceFunctionLibrary.BPFL_GameInstanceFunctionLibrary_C.GetRSGameInstance // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

