// BlueprintGeneratedClass BPFL_MakeEventFunction.BPFL_MakeEventFunction_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_MakeEventFunction_C : UBlueprintFunctionLibrary {

	void SetNoAddEventTriggerCmdFlag(bool Flag, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetNoAddEventTriggerCmdFlag // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CreateMatchIDWidget(int32_t CaptureActorIndex, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CreateMatchIDWidget // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearEventPlayerCostumeSettingAll(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearEventPlayerCostumeSettingAll // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventPlayerCostumeSettingList(struct TArray<enum class EPlayerID> playerId, bool DefaultCostume, bool NoAttachments, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventPlayerCostumeSettingList // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventPlayerCostumeSetting(enum class EPlayerID playerId, bool DefaultCostume, bool NoAttachments, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventPlayerCostumeSetting // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EquipAttachmentSetoMaskEventEnd(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EquipAttachmentSetoMaskEventEnd // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventCacheActorCompsHiddenInGameForTagName(struct FName TagName, bool IsHiddenInGame, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventCacheActorCompsHiddenInGameForTagName // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearEventCacheActorCompsHiddenInGameFromTagName(struct FName TagName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearEventCacheActorCompsHiddenInGameFromTagName // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBrainFieldMonitorImage(struct UMaterialInterface* DrawMaterial, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBrainFieldMonitorImage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetStopEndDriveMode(bool FlagIn, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetStopEndDriveMode // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ResetPsychicObjectArrangeTransform(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ResetPsychicObjectArrangeTransform // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void HiddenAttachmentSetoMask(bool bHidden, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.HiddenAttachmentSetoMask // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetENPCTransform(enum class EPlayerID playerId, struct FTransform Transform, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetENPCTransform // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RemoveAllLockMipPrestreamTextures(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.RemoveAllLockMipPrestreamTextures // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void LockMipPrestreamTextures(struct TArray<struct FName> PrestreamMeshNames, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.LockMipPrestreamTextures // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RemoveMipPrestreamTextures(struct TArray<struct FName> PrestreamMeshNames, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.RemoveMipPrestreamTextures // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AddMipPrestreamTextures(struct TArray<struct FName> PrestreamMeshNames, bool ForceLoad, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.AddMipPrestreamTextures // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CheckBrainFieldRemainTime(float RemainTime, struct UObject* __WorldContext, bool bResult); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CheckBrainFieldRemainTime // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void LoadMakeEventActorClassFromPath(struct FString PathString, struct UObject* __WorldContext, struct AMakeEventActor* AsMake Event Actor); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.LoadMakeEventActorClassFromPath // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ResetStaticGhostTrailCache(int32_t ControlId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ResetStaticGhostTrailCache // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetStaticGhostTrailCache(enum class EPlayerID playerId, int32_t ControlId, int32_t Num, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetStaticGhostTrailCache // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PreloadEventPlayerInstance(struct TArray<enum class EPlayerID> PlayerIDs, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PreloadEventPlayerInstance // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ForceWarpNpcBattleMember(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ForceWarpNpcBattleMember // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void DisableArrangePlaneActors(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.DisableArrangePlaneActors // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EquipAttachmentSetoMask(bool bAddItem, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EquipAttachmentSetoMask // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBrainFieldColor(bool IsPlayer, float Grayscale, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBrainFieldColor // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventHiddenNeonWire(bool Hidden, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventHiddenNeonWire // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBattleMemberToEmpty(enum class EPlayerID playerId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBattleMemberToEmpty // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void Set ENPC Wire Visibility(enum class EPlayerID playerId, bool IsVisible, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.Set ENPC Wire Visibility // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetRenderingSettingArea(int32_t LocationId, int32_t areaId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetRenderingSettingArea // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeEnpcUniqueThinkTable(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeEnpcUniqueThinkTable // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndDriveMode(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndDriveMode // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RestoreAAStaticToInGame(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.RestoreAAStaticToInGame // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearCourtMortBattle(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearCourtMortBattle // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartBattleEm8300(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartBattleEm8300 // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetLogUpdateGoal(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetLogUpdateGoal // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartSasWindow(enum class EPlayerID playerId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartSasWindow // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartEventDirectBrainFieldWarning(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartEventDirectBrainFieldWarning // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StopVibration(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StopVibration // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayVibration(struct UForceFeedbackEffect* VibrationParameterAsset, bool bLooping, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayVibration // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetDrawModeKaren(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetDrawModeKaren // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void DestroyEnemyWithTagName(struct FName TagName, struct UObject* __WorldContext, bool bDummy); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.DestroyEnemyWithTagName // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void Set ENPC Preset Player Camera(bool Enable, enum class EPlayerCameraPreset Preset Basic, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.Set ENPC Preset Player Camera // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetEnemyForTagName(struct FName TagName, struct UObject* __WorldContext, struct AActor* Actor); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.GetEnemyForTagName // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ResetFPS(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ResetFPS // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetFPS(int32_t fps, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetFPS // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEnemyPlayerBattleForTagName(bool bBattle, bool bUseBrainField, struct FName TagName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEnemyPlayerBattleForTagName // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void LoadMakeEventAsset(struct TArray<struct FString> LoadBPEventPathList, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.LoadMakeEventAsset // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RestoreEnemyParameterToTagName(struct FName TagName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.RestoreEnemyParameterToTagName // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void BackupEnemyParameterToTagName(struct FName TagName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.BackupEnemyParameterToTagName // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetWeaponVisibility(bool Visibility, bool NoApply, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetWeaponVisibility // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetDisableActionBoringIdle(bool disable, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetDisableActionBoringIdle // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void MiniTipsStopDraw(enum class EHelpTutorial TipsID, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.MiniTipsStopDraw // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndDelayBattleLog(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndDelayBattleLog // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartDelayBattleLog(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartDelayBattleLog // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ReturnEventRemvoeMembers(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ReturnEventRemvoeMembers // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EventRemvoeMembers(struct TArray<enum class EPlayerID> IgnoreActorList, bool bDisableSAS, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EventRemvoeMembers // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void NaomiChangePhaseParamSetting(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.NaomiChangePhaseParamSetting // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void Set Force Player Mode(bool IsDisableInput, bool IsOnlyWalk, bool IsEnableOpenUiMenu, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.Set Force Player Mode // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetForceCameraMove(bool Active, float LerpTime, struct FVector rootOffset, float camDistance, float FOV, enum class EEasingFunc easeFunc, float easeBlendExp, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetForceCameraMove // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void MiniTipsClose(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.MiniTipsClose // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void MiniTipsOpen(int32_t TipsID, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.MiniTipsOpen // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartExtraSASCutin(enum class ESASCutinExtraID CutinID, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartExtraSASCutin // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UnloadExtraSASCutin(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.UnloadExtraSASCutin // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void LoadExtraSASCutin(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.LoadExtraSASCutin // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void Set Vision Fog In Game(enum class EVisionFogID FogID, float Rate, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.Set Vision Fog In Game // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PadVibrationStop(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PadVibrationStop // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PadVibrationLoopTime(struct UForceFeedbackEffect* VibrationParameterAsset, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PadVibrationLoopTime // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PadVibrationLoop(struct UForceFeedbackEffect* VibrationParameterAsset, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PadVibrationLoop // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PadVibrationOneShot(struct UForceFeedbackEffect* VibrationParameterAsset, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PadVibrationOneShot // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void  Auto Reply Brain Message(struct FName DefaultThreadTitle, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C. Auto Reply Brain Message // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartBrainMessageMenu(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartBrainMessageMenu // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SpawnChildYuito(struct FTransform SpawnTransform, struct UObject* __WorldContext, struct ARSBattlePlayer_C* OutChildYuito); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SpawnChildYuito // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EventControlChildYuito(bool IsControl, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EventControlChildYuito // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventSASEquipStatus(enum class E_SASKindNative kind, enum class ESASEquipStatus Status, bool bNotEquip, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventSASEquipStatus // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeBrainFieldUserEnd(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeBrainFieldUserEnd // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetVisibleBrainKeyGuide(bool visibleflag, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetVisibleBrainKeyGuide // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartCourtMortBattle(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartCourtMortBattle // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartAttentionCamera(bool look at actor, struct FVector look at pos in, struct AActor* target actor in, struct UCurveFloat* actor curve in, bool change fov, float target fov in, struct UCurveFloat* fov curve in, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartAttentionCamera // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndAttentionCamera(struct UCurveFloat* actor curve in, struct UCurveFloat* fov curve in, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndAttentionCamera // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndPartyMemberEventWait(enum class RSPartyPlayerKind kind, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndPartyMemberEventWait // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBattleMemberSASStealth(bool isSetStealth, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBattleMemberSASStealth // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EnemyAllDeadForLevelName(struct TArray<struct FName> levelNameList, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EnemyAllDeadForLevelName // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void FinishLoopPostProcessSequencer(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.FinishLoopPostProcessSequencer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetAllTownNpcAnimation(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetAllTownNpcAnimation // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StopEventPPStream(struct UCurveFloat* NewFloatCurve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StopEventPPStream // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void setEventPPStream(float PerspectiveScaleLeft, float PerspectiveScaleRight, float Rotate, float VisibleLineArea, float EmissivePower, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.setEventPPStream // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetSpecialNodeAddAnimWeightCurve(struct UCurveFloat* Curve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetSpecialNodeAddAnimWeightCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayAddSpecialNodeAnimMontage(struct FString SpecialNodeAnimNamePath, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayAddSpecialNodeAnimMontage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StopAddSpecialNodeAnimMontage(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StopAddSpecialNodeAnimMontage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StopPostProcessSequencer(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StopPostProcessSequencer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetFrameParticleAlphaCurve(int32_t CaptureActorIndex, struct UCurveFloat* Curve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetFrameParticleAlphaCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void DisableEnemyIgnoreDamageOne(enum class ECharacterIgnoreDamage DamageType, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.DisableEnemyIgnoreDamageOne // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EnableEnemyIgnoreDamageOne(enum class ECharacterIgnoreDamage DamageType, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EnableEnemyIgnoreDamageOne // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void DisableEnemyIgnoreDamageAll(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.DisableEnemyIgnoreDamageAll // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EnableEnemyIgnoreDamageAll(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EnableEnemyIgnoreDamageAll // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEnemyHPVisible(bool IsVisible, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEnemyHPVisible // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CreateEventPlAttachAsset(struct FName DTRowName, int32_t CaptureActorIndex, struct FTransform OffsetTransform, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CreateEventPlAttachAsset // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetActorHiddenInGameForTagName(struct FName TagName, bool IsHiddenInGame, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetActorHiddenInGameForTagName // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetForceBrainTalkMode(bool IsActive, struct FName StartFoceBTCameraPresetName, bool IsDisableInput, bool IsOnlyWalk, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetForceBrainTalkMode // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetReturnMovePlayer(bool IsWalk, struct FVector PlayerVelocity, float MoveDistance, struct AActor* CollisionActor, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetReturnMovePlayer // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void InvalidPlayerLookAtLocation(enum class RSPartyPlayerKind PartyPlayerKind, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.InvalidPlayerLookAtLocation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void setPlayerLookAtLocation(enum class RSPartyPlayerKind PartyPlayerKind, struct FVector TargetLocation, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.setPlayerLookAtLocation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsExistBattleMember(enum class EPlayerID playerId, struct UObject* __WorldContext, bool IsExist); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsExistBattleMember // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsPlayerEquipAttachment(enum class EPlayerID PartyPlayerID, int32_t attachmentId, struct UObject* __WorldContext, bool IsEquipAttachment); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsPlayerEquipAttachment // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsPlayerEquipAccessory(enum class EPlayerID PartyPlayerID, int32_t accessoryId, struct UObject* __WorldContext, bool IsEquipAccessory); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsPlayerEquipAccessory // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsPlayerEquipWeapon(enum class EPlayerID PartyPlayerID, int32_t WeaponId, struct UObject* __WorldContext, bool IsEquipWepon); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsPlayerEquipWeapon // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsPlayerEquipCostume(enum class EPlayerID PartyPlayerID, int32_t CostumeId, struct UObject* __WorldContext, bool IsEquipCostume); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsPlayerEquipCostume // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsExistPartyMember(enum class EPlayerID playerId, struct UObject* __WorldContext, bool IsExist); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsExistPartyMember // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RecoverPlayerAllHP(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.RecoverPlayerAllHP // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartPresentSelectMenu(enum class EPlayerID playerId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartPresentSelectMenu // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartPresentCheckMenu(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartPresentCheckMenu // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndSubMenu(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndSubMenu // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsEndSubMenu(struct UObject* __WorldContext, bool IsEndSubMenu); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsEndSubMenu // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PresentGetSelectFlag(struct UObject* __WorldContext, bool SelectFlag); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PresentGetSelectFlag // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PresentGetSelectItemID(struct UObject* __WorldContext, struct FName ItemId); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PresentGetSelectItemID // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CancelTimerByPlayObstructAction(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CancelTimerByPlayObstructAction // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetTimerByPlayObstructAction(float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetTimerByPlayObstructAction // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayBoadCurveValueMontage(int32_t CaptureActorIndex, struct UAnimMontage* AnimMontage, bool IsLoop, struct UCurveFloat* MontageWeghtCurveAsset, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayBoadCurveValueMontage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetLevelActorVisible(bool IsVisible, struct FVector Position, float Range, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetLevelActorVisible // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearEventObstructPsychic(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearEventObstructPsychic // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventObstructPsychic (bool bSAS, bool bPsychic, bool bAttack, bool bDrive, bool bBrainCrash, struct UAnimMontage* ObstructAnimation, struct ULevelSequence* ObstructSequencer, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventObstructPsychic  // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndMatchIDWidget(int32_t CaptureActorIndex, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndMatchIDWidget // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartMatchIDWidget(int32_t CaptureActorIndex, struct FName CharaID, struct FName armyCodeMessageID, struct FVector Scale, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartMatchIDWidget // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetPlayerCharaID(struct UObject* __WorldContext, enum class EPlayerID ReturnPlayerID); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.GetPlayerCharaID // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearPlaneRenderTargetForJointID(struct TArray<struct FName> JointIDList, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearPlaneRenderTargetForJointID // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CallGeneralPresentEvent(struct FName ForCharaID, struct FName ItemId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CallGeneralPresentEvent // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EndPresentSequencer(struct AAjitoMember* BindForCharaActor, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.EndPresentSequencer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayPresentSequencer(struct ULevelSequence* Sequence, struct AAjitoMember* BindForCharaActor, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayPresentSequencer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoadAddAnimWeightCurve(int32_t CaptureActorIndex, struct UCurveFloat* Curve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoadAddAnimWeightCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartRedLight(enum class EBossNameMode Mode, float freeFixedDrawSecond, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartRedLight // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureUVRotateCurveTimeline(int32_t CaptureActorIndex, struct UCurveFloat* UVAngleCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureUVRotateCurveTimeline // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureUVRotateCurve(int32_t CaptureActorIndex, struct UCurveFloat* Curve, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureUVRotateCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureUVRotate(int32_t CaptureActorIndex, float Angle, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureUVRotate // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleXYCurveTimeline(int32_t CaptureActorIndex, struct UCurveFloat* TexScaleXCurve, struct UCurveFloat* TexScaleYCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleXYCurveTimeline // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleXYCurveTimelineWithOffset(int32_t CaptureActorIndex, struct UCurveFloat* ScaleCurveX, struct UCurveFloat* ScaleCurveY, struct UCurveFloat* CenterXCurve, struct UCurveFloat* CenterYCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleXYCurveTimelineWithOffset // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleYCurve(int32_t CaptureActorIndex, struct UCurveFloat* CurveY, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleYCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleXCurve(int32_t CaptureActorIndex, struct UCurveFloat* CurveX, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleXCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleY(int32_t CaptureActorIndex, float ScaleY, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleY // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleX(int32_t CaptureActorIndex, float ScaleX, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleX // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SettingCaptureCrossFadeForAnimCurveDataCommand(int32_t CaptureActorIndex, struct FName CapturePresetName, struct FName CharaAnimationName, struct FName CharaFaceAnimationName, struct FName LightPresetName, struct ULevelSequence* CaptureSequence, float CaptureSequencePosition, struct FName TextureRowName, enum class EStaticPlType StaticPlType, struct FName MovieTextureRowName, struct FName CharaEyePresetName, float EyeXAxisThreshold, float EyeYAxisThreshold, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SettingCaptureCrossFadeForAnimCurveDataCommand // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SettingCaptureCommand(int32_t CaptureActorIndex, int32_t BoardMeshIndex, struct FName CapturePresetName, struct FName CharaBodyAnimationSectionName, struct FName CharaFaceAnimationSectionName, int32_t NpcMeshTableID, int32_t NpcMaterialTableID, struct FName LightPresetName, struct ULevelSequence* CaptureSequnece, float CaptureSequnecePositon, struct FName TextureRowName, enum class EStaticPlType StaticPlType, struct FName MovieTextureRowName, bool IsUseSaveTexture, bool IsSeamlessInGameCapture, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SettingCaptureCommand // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SettingCaptureCrossFadeForAnimCurveData(int32_t CaptureActorIndex, struct FName CapturePresetName, struct FName CharaAnimationName, struct FName CharaFaceAnimationName, struct FName LightPresetName, struct ULevelSequence* CaptureSequence, float CaptureSequencePosition, struct FName TextureRowName, enum class EStaticPlType StaticPlType, struct FName MovieTextureRowName, bool IsSeamlessInGameCapture, struct FName CharaEyePresetName, float EyeXAxisThreshold, float EyeYAxisThreshold, struct FName CharaPartsDTRowName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SettingCaptureCrossFadeForAnimCurveData // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleCenter(int32_t CaptureActorIndex, bool IsScaleLeftBottom, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleCenter // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetPhaseAnimCurveInfo(struct TArray<struct FEventPlAnimationCurveParam> CurrentPlAnimationCurveDataList, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetPhaseAnimCurveInfo // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBattleMember(enum class EPlayerID playerId, enum class RSPartyPlayerKind PartyPlayerKind, bool IsSetMemberEventHidden, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBattleMember // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AutoSave(bool IsDoCapture, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.AutoSave // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CaptureSaveDataIcon(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CaptureSaveDataIcon // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CaptureSceneBGForLevelSequencere(struct ULevelSequence* CaptureSequence, float CaptureSequencePosition, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CaptureSceneBGForLevelSequencere // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartChangeFaceList(int32_t CaptureActorIndex, struct TArray<struct FFChangeFaceData> ChangeFaceDataArray, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartChangeFaceList // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ReturnPartyMember(enum class EPlayerID playerId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ReturnPartyMember // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void RemovePartyMember(enum class EPlayerID playerId, bool bDequipAttachment, bool bDefaultCostume, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.RemovePartyMember // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PresetAddPartyMember(struct FName PresetName, bool isCheckBattleMemberMain, bool bNotEquipSAS, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PresetAddPartyMember // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CaptureSpeakFace(int32_t CaptureActorIndex, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.CaptureSpeakFace // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeCaptureFaceAndBodyAnimation(int32_t CaptureActorIndex, struct FName CharaAnimationName, struct FName CharaFaceAnimationName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeCaptureFaceAndBodyAnimation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetSpeakerCapActor(int32_t CaptureActoeIndex, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetSpeakerCapActor // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayPostProcessSequencer(struct ULevelSequence* Sequence, bool IsLoop, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayPostProcessSequencer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearChildCapActor(enum class EPhaseAlphaCurveType AlphaFadeType, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearChildCapActor // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayPhaseNodeAnimation(struct FString AnimMontagePath, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayPhaseNodeAnimation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartNewStaticInGeneral(struct FString InAnimMontagePath, enum class EShadaAnimeType ShaderAnimType, struct FName SelectShaderAnimeDTRowName, bool NoPlaySE, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartNewStaticInGeneral // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AttachCapActorForPhaseNodeMesh(int32_t CaptureActorIndex, struct FName SocketName, bool NewVisibility, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.AttachCapActorForPhaseNodeMesh // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetNextNewStaticNode(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetNextNewStaticNode // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayPhaseAnimation(struct FString SpecialNodeAnimNamePath, struct FName AttachPointName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayPhaseAnimation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayNodeAnimation(int32_t CaptureActorIndex, struct FString animationNameOrPath, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayNodeAnimation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AttachCapActorForCapActor(int32_t ParentCapActorIndex, int32_t ChildCapActorIndex, struct FName AttachPointName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.AttachCapActorForCapActor // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeSpeakerStaticPl(struct TArray<struct FName> FrontCharaPlBoneNameList, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeSpeakerStaticPl // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ClearSpecialStatic(int32_t ParentSpecialCaptureActorIndex, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ClearSpecialStatic // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlaySpecialNodeAnimMontage(struct FString SpecialNodeAnimNamePath, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlaySpecialNodeAnimMontage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AttachCaptureActorForCaptureActor(int32_t ParentCaptureActorIndex, int32_t ChildCaptureActorIndex, struct FName SocketName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.AttachCaptureActorForCaptureActor // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AttachCapActorForSpecialNodeActor(int32_t CaptureActorIndex, struct FName AttachPointName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.AttachCapActorForSpecialNodeActor // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlaySpecialNodeAnimation(struct FString SpecialNodeAnimNamePath, bool IsLoop, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlaySpecialNodeAnimation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetTownUIMode(bool TownMode, bool AjitoMode, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetTownUIMode // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StopLoopSe(struct FName Name, float FadeTime, float FadeVolume, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StopLoopSe // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayLoopSe(struct FName Name, struct USoundAtomCue* AtomCue, struct FVector Location, float FadeTime, float FadeVolume, bool ContinuousPlaybackSkip, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayLoopSe // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartCrossFadeForCapIndex(int32_t CaptureActorIndex, struct UCurveFloat* Curve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartCrossFadeForCapIndex // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SettingCaptureCrossFadeForCapIndex(int32_t CaptureActorIndex, struct FName CapturePresetName, struct FName CharaAnimationName, struct FName CharaFaceAnimationName, int32_t NpcMeshTableID, int32_t NpcMaterialTableID, struct FName LightPresetName, struct ULevelSequence* CaptureSequence, float CaptureSequencePosition, struct FName TextureRowName, enum class EStaticPlType StaticPlType, struct FName MovieTextureRowName, bool IsSeamlessInGameCapture, struct FName CharaEyePresetName, float EyeXAxisThreshold, float EyeYAxisThreshold, struct FName CharaPartsDTRowName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SettingCaptureCrossFadeForCapIndex // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartCrossFadeCharaCapture(int32_t CaptureActorIndex, struct FName CapturePresetName, struct FName CharaAnimationName, struct FName CharaFaceAnimationName, struct FName LightPresetName, int32_t NpcMeshTableID, int32_t NpcMaterialTableID, struct FName CharaPartsDTRowName, enum class ECharaCapChangeSpeedType ChangeSpeedType, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartCrossFadeCharaCapture // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureOffsetCurveTimeline(int32_t CaptureActorIndex, struct UCurveFloat* TexOffsetXCurve, struct UCurveFloat* TexOffsetYCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureOffsetCurveTimeline // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleCurveTimeline(int32_t CaptureActorIndex, struct UCurveFloat* TexScaleCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleCurveTimeline // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleCurveTimelineWithOffset(int32_t CaptureActorIndex, struct UCurveFloat* ScaleCurve, struct UCurveFloat* CenterXCurve, struct UCurveFloat* CenterYCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleCurveTimelineWithOffset // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEnemyPlayerBattle(bool bBattle, bool bUseBrainField, enum class EPlayerID playerId, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEnemyPlayerBattle // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeCloseBrainField(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeCloseBrainField // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PrivateGetENPC(struct UObject* __WorldContext, struct AActor* ENPC); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PrivateGetENPC // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PrivateGetMainPlayer(struct UObject* __WorldContext, struct AActor* Player); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PrivateGetMainPlayer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeBrainFieldUser(struct AActor* User, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeBrainFieldUser // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeBrainFieldUserENPC(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeBrainFieldUserENPC // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeBrainFieldUserPlayer(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangeBrainFieldUserPlayer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartOverwriteBrainField(struct AActor* User, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartOverwriteBrainField // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartOverwriteBrainFieldENPC(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartOverwriteBrainFieldENPC // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartOverwriteBrainFieldPlayer(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartOverwriteBrainFieldPlayer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartCloseBrainField(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartCloseBrainField // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartOpenBrainField(struct AActor* User, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartOpenBrainField // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartOpenBrainFieldENPC(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartOpenBrainFieldENPC // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartOpenBrainFieldPlayer(struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartOpenBrainFieldPlayer // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetCarsVisible(bool Visible, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetCarsVisible // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetPlayerHPPercent(struct UObject* __WorldContext, float HPPercent); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.GetPlayerHPPercent // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScrollCurveTimeline(int32_t CaptureActorIndex, struct UCurveFloat* TexScrollXCurve, struct UCurveFloat* TexScrollYCurve, float Speed, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScrollCurveTimeline // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEventDisableGameOver(bool bDisable, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetEventDisableGameOver // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetIsAllEnemyEventWeak(bool IsEventWeak, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetIsAllEnemyEventWeak // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetIsAllEnemyEventBerserk(bool IsEventBerserk, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetIsAllEnemyEventBerserk // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetIsAllEnemyEventWait(bool IsEventWait, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetIsAllEnemyEventWait // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartCaptureBGAlphaCurve(struct UCurveFloat* Curve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartCaptureBGAlphaCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartCrossFade(int32_t CaptureActorIndex, struct UCurveFloat* Curve, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartCrossFade // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SettingCaptureCrossFade(int32_t CaptureActorIndex, struct FName CapturePresetName, struct FName CharaAnimationName, struct FName CharaFaceAnimationName, struct FName LightPresetName, struct ULevelSequence* CaptureSequence, float CaptureSequencePosition, struct FName TextureRowName, enum class EStaticPlType StaticPlType, struct FName MovieTextureRowName, bool IsSeamlessInGameCapture, struct FName CharaEyePresetName, float EyeXAxisThreshold, float EyeYAxisThreshold, struct FName CharaPartsDTRowName, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SettingCaptureCrossFade // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetPartyCharacterVisibility(enum class RSPartyPlayerKind PartyPlayerType, bool bVisibility, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetPartyCharacterVisibility // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PlayBoadAddAnimation(int32_t CaptureActorIndex, struct UAnimMontage* AddBordAnimMontage, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.PlayBoadAddAnimation // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ResetPlayerCamera(float ResetSec, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ResetPlayerCamera // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetSpecialCaptureActor(int32_t SpecialCaptureActorIndex, struct UObject* __WorldContext, struct ABPCaptureActor_C* CaptureActor, bool IsSuccess); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.GetSpecialCaptureActor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SettingSpecialCapture(int32_t SpecialCaptureActorIndex, int32_t BoardMeshIndex, struct ULevelSequence* CaptureSequence, float CaptureSequencePosition, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SettingSpecialCapture // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartEventCharaName(int32_t CaptureActorIndex, bool IsSpecialCaptureIndex, struct FName SocketName, struct FString CharaID, struct FVector Scale, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartEventCharaName // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void StartEventBossName(int32_t CaptureActorIndex, bool IsSpecialCaptureIndex, struct FName SocketName, struct FString bossId, struct FVector Scale, enum class EBossNameMode Mode, float freeFixedDrawSecond, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.StartEventBossName // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void IsCharacterEventMoveEnd(enum class RSPartyPlayerKind PartyPlayerType, struct UObject* __WorldContext, bool Result); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.IsCharacterEventMoveEnd // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetCharacterEventMove(enum class RSPartyPlayerKind PartyPlayerType, bool Walk, struct FName EventSplineMovePointTagName, bool bAfterWait, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetCharacterEventMove // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangePlayerCharacter(enum class RSPartyPlayerKind Type, struct ARSCharacterBase* playerClass, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.ChangePlayerCharacter // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScrollSpeedCurve(int32_t CaptureActorIndex, struct UCurveFloat* TexScrollSpeedXCurve, struct UCurveFloat* TexScrollSpeedYCurve, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScrollSpeedCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScrollCurve(int32_t CaptureActorIndex, struct UCurveFloat* TexScrollXCurve, struct UCurveFloat* TexScrollYCurve, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScrollCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScaleCurve(int32_t CaptureActorIndex, struct UCurveFloat* Curve, float Time, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScaleCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScale(int32_t CaptureActorIndex, float Scale, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScale // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardMaterialParamCurve(int32_t CaptureActorIndex, struct FName MaterialParamName, struct UCurveFloat* Curve, float curveTime, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardMaterialParamCurve // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardMaterialParamValue(int32_t CaptureActorIndex, struct FName MaterialParamName, float Value, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardMaterialParamValue // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetCaptureActor(int32_t CaptureActorIndex, struct UObject* __WorldContext, struct ABPCaptureActor_C* CaptureActor, bool IsSuccess); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.GetCaptureActor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardMaterialParam(struct ABPCaptureActor_C* CaptureActor, struct FName MaterialParamName, float ParamValue, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardMaterialParam // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScroll(int32_t CaptureActorIndex, float TexScrollX, float TexScrollY, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScroll // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetBoardTextureScrollSpeed(int32_t CaptureActorIndex, float TexScrollSpeedX, float TexScrollSpeedY, struct UObject* __WorldContext); // Function BPFL_MakeEventFunction.BPFL_MakeEventFunction_C.SetBoardTextureScrollSpeed // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

