// BlueprintGeneratedClass BPFL_MaterialUtility.BPFL_MaterialUtility_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_MaterialUtility_C : UBlueprintFunctionLibrary {

	void SetStealthMaterialSkinMeshParameter(struct USkinnedMeshComponent* SkinnedMeshComp, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SetStealthMaterialSkinMeshParameter // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetStealthMaterialPlayerIDParameter(struct USkinnedMeshComponent* SkinnedMeshComp, enum class EPlayerID playerId, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SetStealthMaterialPlayerIDParameter // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetEm8310ArmTypeVisible(bool SkeletonArm, struct USkeletalMeshComponent* SkelMeshComp, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SetEm8310ArmTypeVisible // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CopyParticleMaterialFromMesh(struct UMeshComponent* BaseMeshComp, int32_t BaseMaterialIndex, struct UParticleSystemComponent* TargetParticleSysComp, struct TArray<int32_t> TargetMaterialIndexList, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.CopyParticleMaterialFromMesh // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ResetMeshMaterials(struct UMeshComponent* MeshComp, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.ResetMeshMaterials // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupMaterialLocationParamFromMesh(struct FName Key, struct UMeshComponent* Mesh, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SetupMaterialLocationParamFromMesh // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupMaterialLocationParamFromMat(struct FName Key, struct TArray<struct UMaterialInstanceDynamic*> MIDs, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SetupMaterialLocationParamFromMat // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetDitherRateEm1400UpperBody(struct USkeletalMeshComponent* SkelMeshComp, float Rate, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SetDitherRateEm1400UpperBody // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangeTranslucecnyNeonWireMaterialDofOFF(struct USkeletalMeshComponent* SkelMeshComp, struct UObject* __WorldContext, bool HasWireMaterial, int32_t WireMaterialIndex, struct UMaterialInterface* BeforeMaterial, struct UMaterialInstanceDynamic* DofOFFWireMaterial); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.ChangeTranslucecnyNeonWireMaterialDofOFF // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetTranslucecnyNeonWireMaterial(struct USkeletalMeshComponent* SkelMeshComp, struct UObject* __WorldContext, bool HasWireMaterial, struct UMaterialInterface* WireMaterial, int32_t WireMaterialIndex); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetTranslucecnyNeonWireMaterial // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMaterialStealthDataAsset(struct UObject* __WorldContext, struct UMaterialStealthParam* StealthParam); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetMaterialStealthDataAsset // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void GetMaterialStealthVelocityRate(struct TArray<struct FVector> LocationHistory, struct UObject* __WorldContext, float Opacity); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetMaterialStealthVelocityRate // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMaterialStealthParamEnemyTimeMax(struct UObject* __WorldContext, float TimeMax); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetMaterialStealthParamEnemyTimeMax // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void GetMaterialStealthParamEnemyFromTime(float Time, struct UObject* __WorldContext, float StealthRate, float BaseMatVanish, bool IsStealthMat); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetMaterialStealthParamEnemyFromTime // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMaterialStealthParamEnemy(float Rate, struct UObject* __WorldContext, float StealthRate, float BaseMatVanish, bool IsStealthMat); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetMaterialStealthParamEnemy // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMaterialStealthParam(float Rate, struct UObject* __WorldContext, float StealthRate, float BaseMatVanish, bool IsStealthMat); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetMaterialStealthParam // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UpdateMaterialPreSkinFacialNormalNPC(struct ANpcSkeletalMeshActor* NpcSkeletalMeshActor, bool IsEvent, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.UpdateMaterialPreSkinFacialNormalNPC // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EnableMaterialPreSkinFacialNormalNPC(struct ANpcSkeletalMeshActor* NpcSkeletalMeshActor, bool Enable, bool IsEvent, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.EnableMaterialPreSkinFacialNormalNPC // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SearchMaterialPreSkinFacialNormalSlots(struct USkeletalMeshComponent* SkeletalMeshComponent, struct UObject* __WorldContext, struct TArray<int32_t> MaterialSlots); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.SearchMaterialPreSkinFacialNormalSlots // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UpdateMaterialPreSkinFacialNormalToSlots(struct USkeletalMeshComponent* SkeletalMeshComponent, bool IsEvent, struct TArray<int32_t> MaterialSlots, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.UpdateMaterialPreSkinFacialNormalToSlots // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UpdateMaterialPreSkinFacialNormal(struct USkeletalMeshComponent* SkeletalMeshComponent, bool IsEvent, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.UpdateMaterialPreSkinFacialNormal // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void EnableMaterialPreSkinFacialNormal(struct USkeletalMeshComponent* SkeletalMeshComponent, bool Enable, bool IsEvent, struct UObject* __WorldContext); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.EnableMaterialPreSkinFacialNormal // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetEnemyBrainCrashWeakColor(bool HighDamage, struct UObject* __WorldContext, struct FLinearColor Color, float Intensity); // Function BPFL_MaterialUtility.BPFL_MaterialUtility_C.GetEnemyBrainCrashWeakColor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

