// BlueprintGeneratedClass BPFL_RenderingUtility.BPFL_RenderingUtility_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_RenderingUtility_C : UBlueprintFunctionLibrary {

	void SetShadowResolution(float TexelsPerPixel, float TexelsPerPixelPointlight, float TexelsPerPixelSpotlight, float TexelsPerPixelRectlight, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetShadowResolution // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetShadowResolution(struct UObject* __WorldContext, float TexelsPerPixel, float TexelsPerPixelPointlight, float TexelsPerPixelSpotlight, float TexelsPerPixelRectlight); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetShadowResolution // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetAAOverrideMainView(bool Override, enum class EOptionAAQuality AAMethod, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetAAOverrideMainView // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupCustomStencilCopyPlayer(bool IsAdd, enum class RSPartyPlayerKind kind, struct ABP_SASCopyPlayerActor_C* CopyPlayer, bool ENPC, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupCustomStencilCopyPlayer // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupCustomStencilCopyENPC(struct ABP_SASCopyPlayerActor_C* CopyENPC, bool Enable, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupCustomStencilCopyENPC // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetCharacterInfiniteBoundsSockets(enum class EPlayerID playerId, struct UObject* __WorldContext, struct TArray<struct FName> Sockets); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetCharacterInfiniteBoundsSockets // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x1685580
	void SetupCustomStencilENPC(struct ARSBattleCharacter_C* ENPC, bool Enable, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupCustomStencilENPC // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CancelCustomStencilSeeThrough(struct UPrimitiveComponent* Primitive, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.CancelCustomStencilSeeThrough // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupAASettingCustom(float CurrentFrameWeight, int32_t SampleCount, float FilterSize, bool UseFXAA, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupAASettingCustom // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupAASetting(enum class EAASettingType AAType, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupAASetting // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetScreenUVRectFromBoundSphere(struct USceneComponent* BoundsComponent, struct APlayerController* PlayerController, struct UObject* __WorldContext, struct FVector4 rect); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetScreenUVRectFromBoundSphere // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetRenderSettingInGame(struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetRenderSettingInGame // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetRenderSettingInMenu(struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetRenderSettingInMenu // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetMenu3DBGRenderLayer(struct UObject* __WorldContext, char RenderLayer); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetMenu3DBGRenderLayer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x1685580
	void GetMenu3DCharacterRenderLayer(struct UObject* __WorldContext, char RenderLayer); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetMenu3DCharacterRenderLayer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x1685580
	void GetNObjStencil(struct UObject* __WorldContext, int32_t Stencil); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetNObjStencil // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void GetSeeThroughStencil(struct UObject* __WorldContext, int32_t Stencil); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetSeeThroughStencil // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void GetAcceleratorStencil(struct UObject* __WorldContext, int32_t Stencil); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetAcceleratorStencil // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void SetupCustomStencilSeeThrough(struct UPrimitiveComponent* Primitive, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupCustomStencilSeeThrough // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ResetNearClip(struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.ResetNearClip // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetNearClip(float Value, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetNearClip // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupCustomStencilPlayer(bool IsAdd, enum class RSPartyPlayerKind kind, struct ARSBattleCharacter_C* Player, bool ENPC, struct UObject* __WorldContext); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.SetupCustomStencilPlayer // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetCustomStencilFromPlayerID(int32_t BaseStencil, int32_t playerId, bool IsAdd, struct UObject* __WorldContext, int32_t SetupStencil); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetCustomStencilFromPlayerID // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetCustomStencilBits(int32_t BaseStencil, int32_t UseBit, int32_t AddStencil, bool IsAdd, struct UObject* __WorldContext, int32_t SetupStencil); // Function BPFL_RenderingUtility.BPFL_RenderingUtility_C.GetCustomStencilBits // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

