// BlueprintGeneratedClass BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_PlayerFunctionLibrary_C : UBlueprintFunctionLibrary {

	void SetHologramCustomStencil(struct UMeshComponent* Mesh, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetHologramCustomStencil // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CheckTelepoAbleTarget(struct AActor* Target, struct UObject* __WorldContext, bool bBattleFieldEnemy); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.CheckTelepoAbleTarget // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ConvertEnumCPPtoBP_PlayerAIMoveMode(enum class EPlayerAIMoveModeCPP CPPEnum, struct UObject* __WorldContext, enum class EPlayerAIMoveMode BPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumCPPtoBP_PlayerAIMoveMode // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumBPtoCPP_PlayerAIMoveMode(enum class EPlayerAIMoveMode BPEnum, struct UObject* __WorldContext, enum class EPlayerAIMoveModeCPP CPPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumBPtoCPP_PlayerAIMoveMode // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumCPPtoBP_PlayerAIBattleThinkTransition(enum class EPlayerAIBattleThinkTransitionCPP CPPEnum, struct UObject* __WorldContext, enum class EPlayerAIBattleThinkTransition BPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumCPPtoBP_PlayerAIBattleThinkTransition // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumBPtoCPP_PlayerAIBattleThinkTransition(enum class EPlayerAIBattleThinkTransition BPEnum, struct UObject* __WorldContext, enum class EPlayerAIBattleThinkTransitionCPP CPPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumBPtoCPP_PlayerAIBattleThinkTransition // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumCPPtoBP_PlayerAIThinkTableType(enum class EPlayerAIThinkTableTypeCPP CPPEnum, struct UObject* __WorldContext, enum class EPlayerAIThinkTableType BPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumCPPtoBP_PlayerAIThinkTableType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumBPtoCPP_PlayerAIThinkTableType(enum class EPlayerAIThinkTableType BPEnum, struct UObject* __WorldContext, enum class EPlayerAIThinkTableTypeCPP CPPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumBPtoCPP_PlayerAIThinkTableType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumCPPtoBP_PlayerAIBattleThinkParam(enum class EPlayerAIBattleThinkParamCPP CPPEnum, struct UObject* __WorldContext, enum class EPlayerAIBattleThinkParam BPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumCPPtoBP_PlayerAIBattleThinkParam // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumBPtoCPP_PlayerAIBattleThinkParam(enum class EPlayerAIBattleThinkParam BPEnum, struct UObject* __WorldContext, enum class EPlayerAIBattleThinkParamCPP CPPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumBPtoCPP_PlayerAIBattleThinkParam // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumCPPtoBP_PlayerAIBattleThinkType(enum class EPlayerAIBattleThinkTypeCPP CPPEnum, struct UObject* __WorldContext, enum class EPlayerAIBattleThinkType BPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumCPPtoBP_PlayerAIBattleThinkType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConvertEnumBPtoCPP_PlayerAIBattleThinkType(enum class EPlayerAIBattleThinkType BPEnum, struct UObject* __WorldContext, enum class EPlayerAIBattleThinkTypeCPP CPPEnum); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ConvertEnumBPtoCPP_PlayerAIBattleThinkType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void GetMaterialParameterHologramDefaultLineColor(struct UObject* __WorldContext, struct FLinearColor Color); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.GetMaterialParameterHologramDefaultLineColor // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologramSASStealth(struct FLinearColor SettingValue, struct TArray<struct UMeshComponent*> CharacterMeshes, struct TArray<struct UMeshComponent*> WeaponMeshes, struct FMaterialSwitchCache InOutStealthSwitch, bool InOutNowStealth, struct TArray<struct UMeshComponent*> AttachmentMeshes, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologramSASStealth // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologramSASCopy(struct FLinearColor CopyColorValue, struct FLinearColor DefaultColor, struct TArray<struct UMeshComponent*> CharacterMeshes, struct TArray<struct UMeshComponent*> WeaponMeshes, struct TArray<struct UMeshComponent*> AttachmentMeshes, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologramSASCopy // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologramSASTelepo(struct FLinearColor SettingValue, struct FLinearColor DefaultColor, struct TArray<struct UMeshComponent*> CharacterMeshes, struct TArray<struct UMeshComponent*> WeaponMeshes, struct TArray<struct UMeshComponent*> AttachmentMeshes, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologramSASTelepo // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologramSASMetal(struct FLinearColor SettingValue, struct TArray<struct UMeshComponent*> CharacterMeshes, struct TArray<struct UMeshComponent*> WeaponMeshes, struct TArray<struct UMeshComponent*> AttachmentMeshes, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologramSASMetal // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologramSAS(struct FLinearColor SettingValue, struct FLinearColor DefaultScanlineColor, enum class E_SASKindNative SasKind, struct TArray<struct USkeletalMeshComponent*> CharacterMeshes, struct TArray<struct USkeletalMeshComponent*> WeaponMeshes, struct FMaterialSwitchCache InOutStealthSwitch, bool InOutNowStealth, struct TArray<struct UMeshComponent*> AttachmentMeshes, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologramSAS // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologramSASCurve(struct UCurveLinearColor* Curve, struct FLinearColor DefaultScanlineColor, float Time, enum class E_SASKindNative SasKind, struct TArray<struct USkeletalMeshComponent*> CharacterMeshes, struct TArray<struct USkeletalMeshComponent*> WeaponMeshes, struct FMaterialSwitchCache InOutStealthSwitch, bool InOutNowStealth, struct TArray<struct UMeshComponent*> AttachmentMeshes, struct UObject* __WorldContext, bool Finish); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologramSASCurve // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetMaterialParameterHologram(struct UMeshComponent* MeshComp, float NoiseRate, float VisibleRate, float EmissiveRate, bool UseVisibleRate, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.SetMaterialParameterHologram // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void ChangePlayerMaterialsHologram(struct UMeshComponent* MeshComp, bool IsWeapon, bool UseCustomStencil, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.ChangePlayerMaterialsHologram // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void Change Player Materials from Slot(struct USkeletalMeshComponent* SkelMeshComp, struct UMaterialInterface* MaterialBody, struct UMaterialInterface* MaterialEye, struct UMaterialInterface* MaterialHair, struct UMaterialInterface* MaterialSkin, struct UMaterialInterface* MaterialOutline, struct UMaterialInterface* MaterialWire0, struct UMaterialInterface* MaterialWire1, struct UMaterialInterface* MaterialMask, struct UMaterialInterface* MaterialOther, struct UObject* __WorldContext); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.Change Player Materials from Slot // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CalcArrowRainLocation(struct AActor* PlayerActor, struct AActor* TargetActor, float CheckUnderHeight, float CHeckUpperHeight, struct UObject* __WorldContext, struct FVector Location); // Function BPFL_PlayerFunctionLibrary.BPFL_PlayerFunctionLibrary_C.CalcArrowRainLocation // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

