// BlueprintGeneratedClass BPFL_RenderingOption.BPFL_RenderingOption_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_RenderingOption_C : UBlueprintFunctionLibrary {

	void PrivateGetDebugQualityPPManager(struct UObject* __WorldContext, bool UseDebugQuality, struct ABP_PostProcessManager_C* PPManager); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.PrivateGetDebugQualityPPManager // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMBrainCrash(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMBrainCrash // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void PrivateGetOptionPostQuality(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.PrivateGetOptionPostQuality // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMSAS(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMSAS // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMDrivePlane(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMDrivePlane // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMLightShaft(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMLightShaft // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMFieldBlur(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMFieldBlur // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMLightUp(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMLightUp // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMBothSideRim(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMBothSideRim // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMGradScreenMask(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMGradScreenMask // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMLuminousSmudge (struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMLuminousSmudge  // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void UseRenderingOptionPPMSoftFocus(struct UObject* __WorldContext, enum class EGradualQuality Quality); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.UseRenderingOptionPPMSoftFocus // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetWindowMode(enum class EWindowMode windowMode, struct UObject* __WorldContext); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.SetWindowMode // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetScreenResolution(int32_t Width, int32_t Height, struct UObject* __WorldContext); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.SetScreenResolution // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetScreenResolutionList(bool IgnoreRefreshRate, struct UObject* __WorldContext, bool Success, struct TArray<struct FScreenResolutionSetting> Resolutions); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.GetScreenResolutionList // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetOptionDisplayBrightness(int32_t Brightness, struct UObject* __WorldContext); // Function BPFL_RenderingOption.BPFL_RenderingOption_C.SetOptionDisplayBrightness // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

