// BlueprintGeneratedClass BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_EnvironmentUtility_C : UBlueprintFunctionLibrary {

	void GetTargetAnySplineComponent(struct USplineComponent* BaseSpline, struct ABP_SplineBase_C* ParentActor, struct UObject* __WorldContext, struct USplineComponent* TargetComponent, bool UseParentSpline); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.GetTargetAnySplineComponent // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetEventCutsceneTransform(enum class ECutsceneRootTransformID CutsceneTransformID, struct FName ExtraName, struct UObject* __WorldContext, struct FTransform Transform); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.GetEventCutsceneTransform // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void DirtyParentSplineActors(struct AActor* SelfActor, struct UObject* __WorldContext); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.DirtyParentSplineActors // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CalcStaticMeshBound(struct TArray<struct UStaticMeshComponent*> StaticMeshes, struct UObject* __WorldContext, struct FVector BoxCenter, struct FVector BoxExtent, struct FVector BoxMin, struct FVector BoxMax); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.CalcStaticMeshBound // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void SetupSplineMaterial(struct UPrimitiveComponent* Primitive, struct TArray<struct UMaterialInterface*> Materials, struct UObject* __WorldContext); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.SetupSplineMaterial // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetTargetSplineComponent(struct USplineComponent* BaseSpline, struct ABP_SplineBase_C* ParentActor, struct UObject* __WorldContext, struct USplineComponent* TargetComponent, bool UseParentSpline); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.GetTargetSplineComponent // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AddInstancedStaticMeshBound(struct UInstancedStaticMeshComponent* InstancedStaticMesh, struct FVector BaseBoundMin, struct FVector BaseBoundMax, struct UObject* __WorldContext, struct FVector BoundMin, struct FVector BoundMax); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.AddInstancedStaticMeshBound // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void AddStaticMeshBound(struct UStaticMeshComponent* StaticMesh, struct FVector BaseBoundMin, struct FVector BaseBoundMax, struct UObject* __WorldContext, struct FVector BoundMin, struct FVector BoundMax); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.AddStaticMeshBound // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void GetWorldBound(struct FVector LocalBoundMin, struct FVector LocalBoundMax, struct FTransform WorldTransform, struct UObject* __WorldContext, struct FVector BoundMin, struct FVector BoundMax); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.GetWorldBound // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
	void CalcSplineBound(struct TArray<struct USplineMeshComponent*> Splines, enum class ESplineMeshAxis ForwardAxis, struct FRotator BaseRotator, bool OneStaticMesh, struct UObject* __WorldContext, struct FVector BoxCenter, struct FVector BoxExtent, struct FVector BoxMin, struct FVector BoxMax); // Function BPFL_EnvironmentUtility.BPFL_EnvironmentUtility_C.CalcSplineBound // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1685580
};

