// Class CosmosWebApi.WebApiConnect
// Size: 0xe8 (Inherited: 0x28)
struct UWebApiConnect : UObject {
	char pad_28[0xa0]; // 0x28(0xa0)
	struct FMulticastInlineDelegate OnReceive; // 0xc8(0x10)
	struct FMulticastInlineDelegate OnError; // 0xd8(0x10)

	struct UWebApiConnect* UserLoginV2(struct UObject* WorldContextObject, struct FString pUserId, struct FString Token, int32_t SkuType); // Function CosmosWebApi.WebApiConnect.UserLoginV2 // (Final|Native|Public|BlueprintCallable) // @ game+0xa87d90
	struct UWebApiConnect* UserLogin(struct UObject* WorldContextObject, struct FString pUserId, struct FString Token, int32_t SkuType); // Function CosmosWebApi.WebApiConnect.UserLogin // (Final|Native|Public|BlueprintCallable) // @ game+0xa87c10
	struct UWebApiConnect* UserLinkBnid(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.UserLinkBnid // (Final|Native|Public|BlueprintCallable) // @ game+0xa87b80
	struct UWebApiConnect* UserGetTrackingNum(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.UserGetTrackingNum // (Final|Native|Public|BlueprintCallable) // @ game+0xa87af0
	struct UWebApiConnect* UserCreate(struct UObject* WorldContextObject, struct FString pUserId, int32_t SkuType); // Function CosmosWebApi.WebApiConnect.UserCreate // (Final|Native|Public|BlueprintCallable) // @ game+0xa879d0
	struct UWebApiConnect* UserConvertUserId(struct UObject* WorldContextObject, struct TArray<struct FString> pUserId); // Function CosmosWebApi.WebApiConnect.UserConvertUserId // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa878a0
	struct UWebApiConnect* UserAuth(struct UObject* WorldContextObject, struct FString pUserId, struct FString Token, int32_t SkuType); // Function CosmosWebApi.WebApiConnect.UserAuth // (Final|Native|Public|BlueprintCallable) // @ game+0xa87720
	struct UWebApiConnect* TusWrite(struct UObject* WorldContextObject, int32_t slotNo, struct FString tusData); // Function CosmosWebApi.WebApiConnect.TusWrite // (Final|Native|Public|BlueprintCallable) // @ game+0xa87600
	struct UWebApiConnect* TusRead(struct UObject* WorldContextObject, struct FString userId, int32_t slotNo); // Function CosmosWebApi.WebApiConnect.TusRead // (Final|Native|Public|BlueprintCallable) // @ game+0xa874e0
	struct UWebApiConnect* TssReadList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.TssReadList // (Final|Native|Public|BlueprintCallable) // @ game+0xa87450
	struct UWebApiConnect* TssRead(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.TssRead // (Final|Native|Public|BlueprintCallable) // @ game+0xa873c0
	struct UWebApiConnect* SysOfflineKpi(struct UObject* WorldContextObject, struct TArray<struct FKpiNoColumnData> KpiNoColumnData); // Function CosmosWebApi.WebApiConnect.SysOfflineKpi // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa872c0
	struct UWebApiConnect* SysKpi(struct UObject* WorldContextObject, struct TArray<struct FKpiNoColumnData> KpiNoColumnData); // Function CosmosWebApi.WebApiConnect.SysKpi // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa871c0
	struct UWebApiConnect* SysGetEnvV2(struct UObject* WorldContextObject, int32_t issureId, struct FString Token, int32_t Region); // Function CosmosWebApi.WebApiConnect.SysGetEnvV2 // (Final|Native|Public|BlueprintCallable) // @ game+0xa87050
	struct UWebApiConnect* SysGetEnv(struct UObject* WorldContextObject, int32_t issureId, struct FString Token); // Function CosmosWebApi.WebApiConnect.SysGetEnv // (Final|Native|Public|BlueprintCallable) // @ game+0xa86f30
	struct UWebApiConnect* SysCheckNgword(struct UObject* WorldContextObject, struct FString word, struct FString Language, int32_t CheckType); // Function CosmosWebApi.WebApiConnect.SysCheckNgword // (Final|Native|Public|BlueprintCallable) // @ game+0xa86db0
	struct UWebApiConnect* SysAgreeKpi(struct UObject* WorldContextObject, int32_t agreeFlg); // Function CosmosWebApi.WebApiConnect.SysAgreeKpi // (Final|Native|Public|BlueprintCallable) // @ game+0xa86cf0
	struct UWebApiConnect* SetHeader(struct UObject* WorldContextObject, struct FString titleCd, struct FString userId, struct FString session, int32_t Platform); // Function CosmosWebApi.WebApiConnect.SetHeader // (Final|Native|Public|BlueprintCallable|BlueprintPure) // @ game+0xa86b20
	void SavedataUploadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FSavedataUploadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.SavedataUploadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	struct UWebApiConnect* SavedataUpload(struct UObject* WorldContextObject, struct FString pUserId, int32_t slotNo, struct FString SlotLabel, struct FString saveData); // Function CosmosWebApi.WebApiConnect.SavedataUpload // (Final|Native|Public|BlueprintCallable) // @ game+0xa86950
	void SavedataMultipartuploadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FSavedataMultipartuploadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.SavedataMultipartuploadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	struct UWebApiConnect* SavedataMultipartupload(struct UObject* WorldContextObject, struct FString pUserId, int32_t slotNo, struct FString SlotLabel, struct FString saveData, struct FString HashKey); // Function CosmosWebApi.WebApiConnect.SavedataMultipartupload // (Final|Native|Public|BlueprintCallable) // @ game+0xa86720
	void SavedataDownloadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FSavedataDownloadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.SavedataDownloadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	struct UWebApiConnect* SavedataDownload(struct UObject* WorldContextObject, struct FString pUserId, int32_t slotNo); // Function CosmosWebApi.WebApiConnect.SavedataDownload // (Final|Native|Public|BlueprintCallable) // @ game+0xa86600
	void SavedataDeleteResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FSavedataDeleteResponseParam respParam); // Function CosmosWebApi.WebApiConnect.SavedataDeleteResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	struct UWebApiConnect* SavedataDelete(struct UObject* WorldContextObject, struct FString pUserId, int32_t slotNo); // Function CosmosWebApi.WebApiConnect.SavedataDelete // (Final|Native|Public|BlueprintCallable) // @ game+0xa864e0
	struct UWebApiConnect* RootBoxRun(struct UObject* WorldContextObject, struct FString rootboxId, struct FString paymentId, int32_t paymentNum, struct FString paymentItemid, int32_t totalPaymentPrice, struct FString campaignId, struct FString country); // Function CosmosWebApi.WebApiConnect.RootBoxRun // (Final|Native|Public|BlueprintCallable) // @ game+0xa86230
	struct UWebApiConnect* RootBoxGetProbability(struct UObject* WorldContextObject, struct FString rootboxId); // Function CosmosWebApi.WebApiConnect.RootBoxGetProbability // (Final|Native|Public|BlueprintCallable) // @ game+0xa86140
	struct UWebApiConnect* RootBoxGetList(struct UObject* WorldContextObject, int32_t listType, struct FString country); // Function CosmosWebApi.WebApiConnect.RootBoxGetList // (Final|Native|Public|BlueprintCallable) // @ game+0xa86020
	struct UWebApiConnect* RootBoxGetDetail(struct UObject* WorldContextObject, struct FString rootboxId); // Function CosmosWebApi.WebApiConnect.RootBoxGetDetail // (Final|Native|Public|BlueprintCallable) // @ game+0xa85f30
	struct UWebApiConnect* RewardEarn(struct UObject* WorldContextObject, struct FString userId, struct FString titleCd, struct FString campaignId, int32_t Method); // Function CosmosWebApi.WebApiConnect.RewardEarn // (Final|Native|Public|BlueprintCallable) // @ game+0xa85d60
	struct UWebApiConnect* RankingSetScore(struct UObject* WorldContextObject, struct FString rankingId, int32_t score, struct FString UserData); // Function CosmosWebApi.WebApiConnect.RankingSetScore // (Final|Native|Public|BlueprintCallable) // @ game+0xa85be0
	struct UWebApiConnect* RankingGetMaster(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.RankingGetMaster // (Final|Native|Public|BlueprintCallable) // @ game+0xa85b50
	struct UWebApiConnect* RankingGetByUser(struct UObject* WorldContextObject, struct FString rankingId, struct TArray<struct FString> userIdList); // Function CosmosWebApi.WebApiConnect.RankingGetByUser // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa859d0
	struct UWebApiConnect* RankingGetByRange(struct UObject* WorldContextObject, struct FString rankingId, int32_t RankingType, int32_t StartRank, int32_t GetNum); // Function CosmosWebApi.WebApiConnect.RankingGetByRange // (Final|Native|Public|BlueprintCallable) // @ game+0xa85840
	struct UWebApiConnect* PointGrantMissionPoint(struct UObject* WorldContextObject, struct FString userId, struct FString titleCd, struct FString campaignId, struct FString keyword); // Function CosmosWebApi.WebApiConnect.PointGrantMissionPoint // (Final|Native|Public|BlueprintCallable) // @ game+0xa85650
	struct UWebApiConnect* PointGrant(struct UObject* WorldContextObject, struct FString userId, struct FString titleCd, struct FString campaignId, int32_t Point); // Function CosmosWebApi.WebApiConnect.PointGrant // (Final|Native|Public|BlueprintCallable) // @ game+0xa85480
	struct UWebApiConnect* PointCardUserList(struct UObject* WorldContextObject, struct FString userId); // Function CosmosWebApi.WebApiConnect.PointCardUserList // (Final|Native|Public|BlueprintCallable) // @ game+0xa85390
	struct UWebApiConnect* PointCardInfo(struct UObject* WorldContextObject, struct FString userId, struct FString titleCd, struct FString campaignId); // Function CosmosWebApi.WebApiConnect.PointCardInfo // (Final|Native|Public|BlueprintCallable) // @ game+0xa85200
	struct UWebApiConnect* PointCardDelete(struct UObject* WorldContextObject, struct FString userId, struct FString titleCd, struct FString campaignId); // Function CosmosWebApi.WebApiConnect.PointCardDelete // (Final|Native|Public|BlueprintCallable) // @ game+0xa85070
	struct UWebApiConnect* MissionInfo(struct UObject* WorldContextObject, struct FString missionId); // Function CosmosWebApi.WebApiConnect.MissionInfo // (Final|Native|Public|BlueprintCallable) // @ game+0xa84f80
	struct UWebApiConnect* MissionGetList(struct UObject* WorldContextObject, struct FString titleCd, struct FString keyword); // Function CosmosWebApi.WebApiConnect.MissionGetList // (Final|Native|Public|BlueprintCallable) // @ game+0xa84e30
	struct UWebApiConnect* LoginBonusGetList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.LoginBonusGetList // (Final|Native|Public|BlueprintCallable) // @ game+0xa84da0
	struct UWebApiConnect* LoginBonusGetInfo(struct UObject* WorldContextObject, struct TArray<struct FString> loginBonusIdList); // Function CosmosWebApi.WebApiConnect.LoginBonusGetInfo // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa84c70
	struct UWebApiConnect* LoginBonusGetBonus(struct UObject* WorldContextObject, struct TArray<struct FString> loginBonusIdList); // Function CosmosWebApi.WebApiConnect.LoginBonusGetBonus // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa84b40
	struct UWebApiConnect* LoginBonusComplete(struct UObject* WorldContextObject, struct FString workId); // Function CosmosWebApi.WebApiConnect.LoginBonusComplete // (Final|Native|Public|BlueprintCallable) // @ game+0xa84a50
	struct UWebApiConnect* ItemUseOwned(struct UObject* WorldContextObject, struct TArray<struct FCosmosItemInfo> itemList); // Function CosmosWebApi.WebApiConnect.ItemUseOwned // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa84920
	struct UWebApiConnect* ItemGetOwned(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.ItemGetOwned // (Final|Native|Public|BlueprintCallable) // @ game+0xa84890
	struct UWebApiConnect* ItemGetMaster(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.ItemGetMaster // (Final|Native|Public|BlueprintCallable) // @ game+0xa84800
	struct UWebApiConnect* ItemAddOwned(struct UObject* WorldContextObject, struct TArray<struct FCosmosItemInfo> itemList); // Function CosmosWebApi.WebApiConnect.ItemAddOwned // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa846d0
	struct UWebApiConnect* Initialize(struct UObject* WorldContextObject, struct FString baseUrl, float limitsec); // Function CosmosWebApi.WebApiConnect.Initialize // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0xa845a0
	struct UWebApiConnect* HugeTssReadList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.HugeTssReadList // (Final|Native|Public|BlueprintCallable) // @ game+0xa84510
	struct UWebApiConnect* HugeTssRead(struct UObject* WorldContextObject, int32_t slotNo); // Function CosmosWebApi.WebApiConnect.HugeTssRead // (Final|Native|Public|BlueprintCallable) // @ game+0xa84450
	struct UWebApiConnect* HugeTssMultiReadList(struct UObject* WorldContextObject, int32_t Region, int32_t purpose, int32_t Language); // Function CosmosWebApi.WebApiConnect.HugeTssMultiReadList // (Final|Native|Public|BlueprintCallable) // @ game+0xa84310
	struct UWebApiConnect* HugeTssMultiRead(struct UObject* WorldContextObject, int32_t slotNo, int32_t Region, int32_t purpose, int32_t Language); // Function CosmosWebApi.WebApiConnect.HugeTssMultiRead // (Final|Native|Public|BlueprintCallable) // @ game+0xa84190
	struct UWebApiConnect* GuildSetPosition(struct UObject* WorldContextObject, struct FString TargetID, int32_t Position); // Function CosmosWebApi.WebApiConnect.GuildSetPosition // (Final|Native|Public|BlueprintCallable) // @ game+0xa84070
	struct UWebApiConnect* GuildSecession(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GuildSecession // (Final|Native|Public|BlueprintCallable) // @ game+0xa83fe0
	struct UWebApiConnect* GuildPositionPermission(struct UObject* WorldContextObject, int32_t positionNo, struct TArray<struct FGuildPermissionInfo> permissionList); // Function CosmosWebApi.WebApiConnect.GuildPositionPermission // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa83eb0
	struct UWebApiConnect* GuildNotificationSelf(struct UObject* WorldContextObject, struct FString guildId); // Function CosmosWebApi.WebApiConnect.GuildNotificationSelf // (Final|Native|Public|BlueprintCallable) // @ game+0xa83dc0
	struct UWebApiConnect* GuildNotification(struct UObject* WorldContextObject, struct FString TargetID); // Function CosmosWebApi.WebApiConnect.GuildNotification // (Final|Native|Public|BlueprintCallable) // @ game+0xa83cd0
	struct UWebApiConnect* GuildInvitedList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GuildInvitedList // (Final|Native|Public|BlueprintCallable) // @ game+0xa83c40
	struct UWebApiConnect* GuildInvitationList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GuildInvitationList // (Final|Native|Public|BlueprintCallable) // @ game+0xa83bb0
	struct UWebApiConnect* GuildInvitationCancel(struct UObject* WorldContextObject, struct FString userId); // Function CosmosWebApi.WebApiConnect.GuildInvitationCancel // (Final|Native|Public|BlueprintCallable) // @ game+0xa83ac0
	struct UWebApiConnect* GuildInvitation(struct UObject* WorldContextObject, struct FString userId); // Function CosmosWebApi.WebApiConnect.GuildInvitation // (Final|Native|Public|BlueprintCallable) // @ game+0xa839d0
	struct UWebApiConnect* GuildInfo(struct UObject* WorldContextObject, struct FString guildId); // Function CosmosWebApi.WebApiConnect.GuildInfo // (Final|Native|Public|BlueprintCallable) // @ game+0xa838e0
	struct UWebApiConnect* GuildGetList(struct UObject* WorldContextObject, int32_t viewNum, int32_t pageNum); // Function CosmosWebApi.WebApiConnect.GuildGetList // (Final|Native|Public|BlueprintCallable) // @ game+0xa837e0
	struct UWebApiConnect* GuildExpulsion(struct UObject* WorldContextObject, struct FString userId); // Function CosmosWebApi.WebApiConnect.GuildExpulsion // (Final|Native|Public|BlueprintCallable) // @ game+0xa836f0
	struct UWebApiConnect* GuildEditMemberData(struct UObject* WorldContextObject, struct FString memberData); // Function CosmosWebApi.WebApiConnect.GuildEditMemberData // (Final|Native|Public|BlueprintCallable) // @ game+0xa83600
	struct UWebApiConnect* GuildEdit(struct UObject* WorldContextObject, struct FString guildData); // Function CosmosWebApi.WebApiConnect.GuildEdit // (Final|Native|Public|BlueprintCallable) // @ game+0xa83510
	struct UWebApiConnect* GuildCreate(struct UObject* WorldContextObject, struct FString guildData, struct FString guildMemberData); // Function CosmosWebApi.WebApiConnect.GuildCreate // (Final|Native|Public|BlueprintCallable) // @ game+0xa833c0
	struct UWebApiConnect* GuildChangeLeader(struct UObject* WorldContextObject, struct FString TargetID); // Function CosmosWebApi.WebApiConnect.GuildChangeLeader // (Final|Native|Public|BlueprintCallable) // @ game+0xa832d0
	struct UWebApiConnect* GuildChangeBasePosition(struct UObject* WorldContextObject, int32_t changeType, int32_t positionNo); // Function CosmosWebApi.WebApiConnect.GuildChangeBasePosition // (Final|Native|Public|BlueprintCallable) // @ game+0xa831d0
	struct UWebApiConnect* GuildApprovalList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GuildApprovalList // (Final|Native|Public|BlueprintCallable) // @ game+0xa83140
	struct UWebApiConnect* GuildApprovalAdd(struct UObject* WorldContextObject, struct FString userId, int32_t judgment); // Function CosmosWebApi.WebApiConnect.GuildApprovalAdd // (Final|Native|Public|BlueprintCallable) // @ game+0xa83020
	struct UWebApiConnect* GuildAddApplyList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GuildAddApplyList // (Final|Native|Public|BlueprintCallable) // @ game+0xa82f90
	struct UWebApiConnect* GuildAddApplyCancel(struct UObject* WorldContextObject, struct FString guildId); // Function CosmosWebApi.WebApiConnect.GuildAddApplyCancel // (Final|Native|Public|BlueprintCallable) // @ game+0xa82ea0
	struct UWebApiConnect* GuildAddApply(struct UObject* WorldContextObject, struct FString guildId); // Function CosmosWebApi.WebApiConnect.GuildAddApply // (Final|Native|Public|BlueprintCallable) // @ game+0xa82db0
	struct UWebApiConnect* GuildAdd(struct UObject* WorldContextObject, struct FString guildId, int32_t judgment); // Function CosmosWebApi.WebApiConnect.GuildAdd // (Final|Native|Public|BlueprintCallable) // @ game+0xa82c90
	struct UWebApiConnect* GiftBoxOpen(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GiftBoxOpen // (Final|Native|Public|BlueprintCallable) // @ game+0xa82c00
	struct UWebApiConnect* GiftBoxClose(struct UObject* WorldContextObject, struct TArray<struct FString> giftIdList); // Function CosmosWebApi.WebApiConnect.GiftBoxClose // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa82ad0
	void GetUserLoginV2Response(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserLoginV2ResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserLoginV2Response // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa82510
	void GetUserLoginResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserLoginResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserLoginResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa827f0
	void GetUserLinkBnidResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserLinkBnidResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserLinkBnidResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa82960
	void GetUserGetTrackingNumResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserGetTrackingNumResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserGetTrackingNumResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetUserCreateResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserCreateResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserCreateResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa827f0
	void GetUserConvertUserIdResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserConvertUserIdResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserConvertUserIdResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa82680
	void GetUserAuthResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FUserAuthResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetUserAuthResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa82510
	void GetTusWriteResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetTusWriteResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetTusReadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FTusReadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetTusReadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetTssReadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FTssReadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetTssReadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetTssReadListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FTssReadListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetTssReadListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa823a0
	void GetSysOfflineKpiResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetSysOfflineKpiResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetSysKpiResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetSysKpiResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetSysGetEnvV2Response(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FSysGetEnvV2ResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetSysGetEnvV2Response // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ef40
	void GetSysGetEnvResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FSysGetEnvResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetSysGetEnvResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetSysCheckNgwordResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetSysCheckNgwordResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetSysAgreeKpiResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetSysAgreeKpiResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetRootBoxRunResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRootBoxRunResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRootBoxRunResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa82230
	void GetRootBoxGetProbabilityResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRootBoxGetProbabilityResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRootBoxGetProbabilityResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa820b0
	void GetRootBoxGetListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRootBoxGetListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRootBoxGetListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81f40
	void GetRootBoxGetDetailResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRootBoxGetDetailResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRootBoxGetDetailResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81d60
	void GetRewardEarnResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRewardEarnResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRewardEarnResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e6c0
	void GetRankingSetScoreResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRankingSetScoreResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetRankingGetMasterResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRankingGetMasterResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRankingGetMasterResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81bf0
	void GetRankingGetByUserResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRankingGetByUserResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRankingGetByUserResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81a80
	void GetRankingGetByRangeResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FRankingGetByRangeResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetRankingGetByRangeResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81910
	void GetPointGrantResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetPointGrantResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetPointGrantMissionPointResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetPointGrantMissionPointResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetPointCardUserListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FPointCardUserListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetPointCardUserListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa817a0
	void GetPointCardInfoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FPointCardInfoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetPointCardInfoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa815f0
	void GetPointCardDeleteResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetPointCardDeleteResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetMissionInfoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FMissionInfoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetMissionInfoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81460
	void GetMissionGetListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FMissionGetListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetMissionGetListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa812f0
	void GetLoginBonusGetListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FLoginBonusGetListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetLoginBonusGetListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81180
	void GetLoginBonusGetInfoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FLoginBonusGetInfoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetLoginBonusGetInfoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa81010
	void GetLoginBonusGetBonusResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FLoginBonusGetBonusResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetLoginBonusGetBonusResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80e90
	void GetLoginBonusCompleteResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetLoginBonusCompleteResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetItemUseOwnedResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetItemUseOwnedResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetItemGetOwnedResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FItemGetOwnedResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetItemGetOwnedResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80d20
	void GetItemGetMasterResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FItemGetMasterResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetItemGetMasterResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80bb0
	void GetItemAddOwnedResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetItemAddOwnedResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetHugeTssReadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FHugeTssReadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetHugeTssReadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ef40
	void GetHugeTssReadListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FHugeTssReadListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetHugeTssReadListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80a40
	void GetHugeTssMultiReadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FHugeTssMultiReadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetHugeTssMultiReadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetHugeTssMultiReadListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FHugeTssMultiReadListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetHugeTssMultiReadListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa808d0
	void GetGuildSetPositionResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildSetPositionResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildSecessionResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildSecessionResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildPositionPermissionResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildPositionPermissionResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildNotificationSelfResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildNotificationSelfResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildNotificationSelfResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80760
	void GetGuildNotificationResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildNotificationResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildNotificationResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80760
	void GetGuildInvitedListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildInvitedListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildInvitedListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80160
	void GetGuildInvitationResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildInvitationResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildInvitationListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildInvitationListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildInvitationListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa802d0
	void GetGuildInvitationCancelResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildInvitationCancelResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildInfoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildInfoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildInfoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa805c0
	void GetGuildGetListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildGetListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildGetListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80160
	void GetGuildExpulsionResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildExpulsionResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildEditResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildEditResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildEditResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80440
	void GetGuildEditMemberDataResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildEditMemberDataResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildCreateResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildCreateResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildCreateResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetGuildChangeLeaderResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildChangeLeaderResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildChangeBasePositionResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildChangeBasePositionResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildApprovalListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildApprovalListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildApprovalListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa802d0
	void GetGuildApprovalAddResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildApprovalAddResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildAddResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildAddResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildAddApplyResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildAddApplyResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGuildAddApplyListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGuildAddApplyListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildAddApplyListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa80160
	void GetGuildAddApplyCancelResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGuildAddApplyCancelResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGiftBoxOpenResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGiftBoxOpenResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGiftBoxOpenResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7fff0
	void GetGiftBoxCloseResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGiftBoxCloseResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetGamecurrencyGetOwnedResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGamecurrencyGetOwnedResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGamecurrencyGetOwnedResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7fe60
	void GetGamecurrencyGetLimitedOwnedResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FGamecurrencyGetLimitedOwnedResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetGamecurrencyGetLimitedOwnedResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7fcf0
	void GetFesJoinResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetFesJoinResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetFesGetRewardResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FFesGetRewardResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetFesGetRewardResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7fb70
	void GetFesGetListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FFesGetListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetFesGetListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7fa00
	void GetFesGetInfoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FFesGetInfoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetFesGetInfoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f7f0
	void GetFesCompleteResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetFesCompleteResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetFesAddPointResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FFesAddPointResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetFesAddPointResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f6a0
	void GetDataupWriteResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FDataupWriteResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetDataupWriteResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f530
	void GetDataupSearchResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FDataupSearchResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetDataupSearchResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f3c0
	void GetDataupReadResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FDataupReadResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetDataupReadResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f200
	void GetDataupAppendResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetDataupAppendResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7f0b0
	void GetCommonpurchaseTokushoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonpurchaseTokushoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCommonpurchaseTokushoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ef40
	void GetCommonpurchaseStartPurchaseResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonpurchaseStartPurchaseResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCommonpurchaseStartPurchaseResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ef40
	void GetCommonpurchaseGetPurchaseStatusResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonpurchaseGetPurchaseStatusResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCommonpurchaseGetPurchaseStatusResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ef40
	void GetCommonpurchaseGetCatalogResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonpurchaseGetCatalogResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCommonpurchaseGetCatalogResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7edd0
	void GetCommonpurchaseCompletePurchaseResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonpurchaseCompletePurchaseResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCommonpurchaseCompletePurchaseResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ec80
	void GetCommonpurchaseCancelPurchaseResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCommonpurchaseCancelPurchaseResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCommonpurchaseCancelPurchaseResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7ec80
	void GetCatalogGetRegionResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCatalogGetRegionResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCatalogGetRegionResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7eb10
	void GetCatalogGetLobbyResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCatalogGetLobbyResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCatalogGetLobbyResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e9a0
	void GetCatalogGetAreaResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCatalogGetAreaResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCatalogGetAreaResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e830
	void GetCampaignTitleListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCampaignTitleListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCampaignTitleListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e3a0
	void GetCampaignRewardListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCampaignRewardListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCampaignRewardListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e6c0
	void GetCampaignInfoResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCampaignInfoResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCampaignInfoResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e510
	void GetCampaignGetListResponse(struct UNetMessage* Data, struct FResponseHeader respHeader, struct FCampaignGetListResponseParam respParam); // Function CosmosWebApi.WebApiConnect.GetCampaignGetListResponse // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xa7e3a0
	struct UWebApiConnect* GamecurrencyGetOwned(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.GamecurrencyGetOwned // (Final|Native|Public|BlueprintCallable) // @ game+0xa7e310
	struct UWebApiConnect* GamecurrencyGetLimitedOwned(struct UObject* WorldContextObject, struct FString date); // Function CosmosWebApi.WebApiConnect.GamecurrencyGetLimitedOwned // (Final|Native|Public|BlueprintCallable) // @ game+0xa7e220
	struct UWebApiConnect* FesJoin(struct UObject* WorldContextObject, struct FString fesId, int32_t factionsNo); // Function CosmosWebApi.WebApiConnect.FesJoin // (Final|Native|Public|BlueprintCallable) // @ game+0xa7e100
	struct UWebApiConnect* FesGetReward(struct UObject* WorldContextObject, struct FString fesId); // Function CosmosWebApi.WebApiConnect.FesGetReward // (Final|Native|Public|BlueprintCallable) // @ game+0xa7e010
	struct UWebApiConnect* FesGetList(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.FesGetList // (Final|Native|Public|BlueprintCallable) // @ game+0xa7df80
	struct UWebApiConnect* FesGetInfo(struct UObject* WorldContextObject, struct FString fesId); // Function CosmosWebApi.WebApiConnect.FesGetInfo // (Final|Native|Public|BlueprintCallable) // @ game+0xa7de90
	struct UWebApiConnect* FesComplete(struct UObject* WorldContextObject, struct FString workId); // Function CosmosWebApi.WebApiConnect.FesComplete // (Final|Native|Public|BlueprintCallable) // @ game+0xa7dda0
	struct UWebApiConnect* FesAddPoint(struct UObject* WorldContextObject, struct FString fesId, int32_t factionsNo); // Function CosmosWebApi.WebApiConnect.FesAddPoint // (Final|Native|Public|BlueprintCallable) // @ game+0xa7dc80
	struct UWebApiConnect* DataupWrite(struct UObject* WorldContextObject, struct FString RequestID, struct FString Data, struct FString appendInfo, struct FDataupSearchTagInfo searchTagInfo); // Function CosmosWebApi.WebApiConnect.DataupWrite // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa7da30
	struct UWebApiConnect* DataupSearch(struct UObject* WorldContextObject, struct TArray<struct FDataupSearchConditionInfo> searchConditionList, int32_t viewNum, int32_t pageNum, int32_t sortColumn, int32_t SortType); // Function CosmosWebApi.WebApiConnect.DataupSearch // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa7d810
	struct UWebApiConnect* DataupRead(struct UObject* WorldContextObject, struct FString RequestID); // Function CosmosWebApi.WebApiConnect.DataupRead // (Final|Native|Public|BlueprintCallable) // @ game+0xa7d720
	struct UWebApiConnect* DataupAppend(struct UObject* WorldContextObject, struct FString RequestID, struct FString appendInfo, struct TArray<struct FDataupUpdateSearchTagInfo> updateSearchTagList); // Function CosmosWebApi.WebApiConnect.DataupAppend // (Final|Native|Public|HasOutParms|BlueprintCallable) // @ game+0xa7d560
	struct UWebApiConnect* CommonpurchaseTokusho(struct UObject* WorldContextObject, struct FString Language); // Function CosmosWebApi.WebApiConnect.CommonpurchaseTokusho // (Final|Native|Public|BlueprintCallable) // @ game+0xa7d470
	struct UWebApiConnect* CommonpurchaseStartPurchase(struct UObject* WorldContextObject, struct FString country, struct FString Language, struct FString Token, struct FString catalogId, struct FString Label); // Function CosmosWebApi.WebApiConnect.CommonpurchaseStartPurchase // (Final|Native|Public|BlueprintCallable) // @ game+0xa7d230
	struct UWebApiConnect* CommonpurchaseGetPurchaseStatus(struct UObject* WorldContextObject, struct FString country, struct FString Language, struct FString Token, struct FString Label); // Function CosmosWebApi.WebApiConnect.CommonpurchaseGetPurchaseStatus // (Final|Native|Public|BlueprintCallable) // @ game+0xa7d040
	struct UWebApiConnect* CommonpurchaseGetCatalog(struct UObject* WorldContextObject, struct FString country, struct FString Language, struct FString Token, struct FString Label); // Function CosmosWebApi.WebApiConnect.CommonpurchaseGetCatalog // (Final|Native|Public|BlueprintCallable) // @ game+0xa7ce50
	struct UWebApiConnect* CommonpurchaseCompletePurchase(struct UObject* WorldContextObject, struct FString country, struct FString Language, struct FString Token, struct FString orderId, struct FString purchaseInfoId); // Function CosmosWebApi.WebApiConnect.CommonpurchaseCompletePurchase // (Final|Native|Public|BlueprintCallable) // @ game+0xa7cc10
	struct UWebApiConnect* CommonpurchaseCancelPurchase(struct UObject* WorldContextObject, struct FString purchaseInfoId, struct FString Token, struct FString errorId, struct FString errorMessage); // Function CosmosWebApi.WebApiConnect.CommonpurchaseCancelPurchase // (Final|Native|Public|BlueprintCallable) // @ game+0xa7ca20
	struct UWebApiConnect* CatalogGetRegion(struct UObject* WorldContextObject); // Function CosmosWebApi.WebApiConnect.CatalogGetRegion // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c990
	struct UWebApiConnect* CatalogGetLobby(struct UObject* WorldContextObject, struct FString areaId); // Function CosmosWebApi.WebApiConnect.CatalogGetLobby // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c8a0
	struct UWebApiConnect* CatalogGetArea(struct UObject* WorldContextObject, struct FString regionId); // Function CosmosWebApi.WebApiConnect.CatalogGetArea // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c7b0
	struct UWebApiConnect* CampaignTitleList(struct UObject* WorldContextObject, struct FString titleCd, int32_t dataType); // Function CosmosWebApi.WebApiConnect.CampaignTitleList // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c690
	struct UWebApiConnect* CampaignRewardList(struct UObject* WorldContextObject, struct FString titleCd, struct FString campaignId, int32_t listType); // Function CosmosWebApi.WebApiConnect.CampaignRewardList // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c510
	struct UWebApiConnect* CampaignInfo(struct UObject* WorldContextObject, struct FString campaignId); // Function CosmosWebApi.WebApiConnect.CampaignInfo // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c420
	struct UWebApiConnect* CampaignGetList(struct UObject* WorldContextObject, int32_t dataType); // Function CosmosWebApi.WebApiConnect.CampaignGetList // (Final|Native|Public|BlueprintCallable) // @ game+0xa7c360
};

