// UserDefinedEnum enum_ui_pk_action_icon_1_animation.enum_ui_pk_action_icon_1_animation
enum class enum_ui_pk_action_icon_1_animation : uint8 {
	NewEnumerator1,
	NewEnumerator2,
	NewEnumerator3,
	NewEnumerator6,
	NewEnumerator10,
	NewEnumerator11,
	NewEnumerator12,
	NewEnumerator13,
	NewEnumerator14,
	NewEnumerator18,
	NewEnumerator19,
	NewEnumerator20,
	NewEnumerator21,
	NewEnumerator22,
	NewEnumerator23,
	NewEnumerator24,
	NewEnumerator25,
	NewEnumerator26,
	NewEnumerator27,
	NewEnumerator28,
	NewEnumerator29,
	NewEnumerator30,
	NewEnumerator31,
	NewEnumerator5,
	enum_ui_pk_action_icon_1_MAX,
};

