// UserDefinedEnum EPlayerAnimMontage.EPlayerAnimMontage
enum class EPlayerAnimMontage : uint8 {
	NewEnumerator0,
	NewEnumerator1,
	NewEnumerator2,
	NewEnumerator3,
	NewEnumerator4,
	NewEnumerator5,
	NewEnumerator6,
	NewEnumerator7,
	NewEnumerator8,
	NewEnumerator10,
	NewEnumerator11,
	NewEnumerator12,
	NewEnumerator13,
	NewEnumerator14,
	NewEnumerator15,
	NewEnumerator19,
	NewEnumerator20,
	NewEnumerator17,
	NewEnumerator21,
	NewEnumerator22,
	NewEnumerator23,
	NewEnumerator24,
	NewEnumerator25,
	NewEnumerator26,
	NewEnumerator27,
	NewEnumerator28,
	NewEnumerator29,
	NewEnumerator30,
	NewEnumerator31,
	EPlayerAnimMontage_MAX,
};

