// BlueprintGeneratedClass HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UHitCheckConvertFuncLibrary_C : UBlueprintFunctionLibrary {

	void GetSkillParameterTable(struct UDataTable* Table, struct FName Name, struct UObject* __WorldContext, struct FHCSkillCommonInfo SkillParam); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.GetSkillParameterTable // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void RuntimeDataToC(struct FCollisionRumtimeDataBP In, struct UObject* __WorldContext, struct FHCRuntimeData Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.RuntimeDataToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void HitResultToC(struct FCommonHitResultBP In, struct UObject* __WorldContext, struct FHCHitResult Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.HitResultToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void RuntimeDataToBP(struct FHCRuntimeData In, struct UObject* __WorldContext, struct FCollisionRumtimeDataBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.RuntimeDataToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionValueDataToBP(struct FHCCollisionValueData In, struct UObject* __WorldContext, struct FCollisionValueDataBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionValueDataToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConditionDataToBP(struct FHCCollisionConditionData In, struct UObject* __WorldContext, struct FCollitionConditionDataBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ConditionDataToBP // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ElementDataToBP(struct FHCCollisionElementData In, struct UObject* __WorldContext, struct FCollisionElementDataBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ElementDataToBP // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionValueKindToBP(enum class HCCollisionValueKind NewParam, struct UObject* __WorldContext, enum class CollisionValueKindBP NewParam1); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionValueKindToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConditionKindToBP(enum class ConditionKind In, struct UObject* __WorldContext, enum class ConditionKindBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ConditionKindToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ElementKindToBP(enum class HCElementKind In, struct UObject* __WorldContext, enum class ElementKindBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ElementKindToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionHitTeamToBP(enum class HCCollisionHitTeam In, struct UObject* __WorldContext, enum class CollisionHitTeamBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionHitTeamToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void DamageKindToBP(enum class HCDamageKind In, struct UObject* __WorldContext, enum class DamageKindBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.DamageKindToBP // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionCommonInfoToBP(struct FHCCollisionCommonInfo In, struct UObject* __WorldContext, struct FCollisionCommonInfoBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionCommonInfoToBP // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void HitResultToBP(struct FHCHitResult In, struct UObject* __WorldContext, struct FCommonHitResultBP Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.HitResultToBP // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void AttackCollisionInfoToC(struct FAttackCollisionInfoBP In, struct UObject* __WorldContext, struct FHCAttackCollisionInfo Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.AttackCollisionInfoToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionValueDataToC(struct FCollisionValueDataBP In, struct UObject* __WorldContext, struct FHCCollisionValueData Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionValueDataToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConditionDataToC(struct FCollitionConditionDataBP In, struct UObject* __WorldContext, struct FHCCollisionConditionData Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ConditionDataToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ElementDataToC(struct FCollisionElementDataBP In, struct UObject* __WorldContext, struct FHCCollisionElementData Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ElementDataToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionCommonInfoToC(struct FCollisionCommonInfoBP In, struct UObject* __WorldContext, struct FHCCollisionCommonInfo Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionCommonInfoToC // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionHitTeamToC(enum class CollisionHitTeamBP In, struct UObject* __WorldContext, enum class HCCollisionHitTeam Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionHitTeamToC // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void DamageKindToC(enum class DamageKindBP In, struct UObject* __WorldContext, enum class HCDamageKind Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.DamageKindToC // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void CollisionValueKindToC(enum class CollisionValueKindBP In, struct UObject* __WorldContext, enum class HCCollisionValueKind Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.CollisionValueKindToC // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ConditionKindToC(enum class ConditionKindBP In, struct UObject* __WorldContext, enum class ConditionKind Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ConditionKindToC // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
	void ElementKindToC(enum class ElementKindBP In, struct UObject* __WorldContext, enum class HCElementKind Out); // Function HitCheckConvertFuncLibrary.HitCheckConvertFuncLibrary_C.ElementKindToC // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1685580
};

