// UserDefinedEnum PsychicObjectGroupID.PsychicObjectGroupID
enum class PsychicObjectGroupID : uint8 {
	NewEnumerator7,
	NewEnumerator8,
	NewEnumerator9,
	NewEnumerator10,
	NewEnumerator11,
	NewEnumerator12,
	NewEnumerator13,
	NewEnumerator14,
	NewEnumerator15,
	NewEnumerator16,
	NewEnumerator17,
	NewEnumerator18,
	NewEnumerator19,
	NewEnumerator3,
	NewEnumerator0,
	NewEnumerator1,
	NewEnumerator2,
	NewEnumerator4,
	NewEnumerator5,
	NewEnumerator6,
	NewEnumerator20,
	NewEnumerator21,
	NewEnumerator22,
	NewEnumerator23,
	NewEnumerator24,
	NewEnumerator25,
	PsychicObjectGroupID_MAX,
};

